/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artist {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'imageUrl' : string,
  'genre' : string,
}
export interface Release {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'artistId' : bigint,
  'genre' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArtist' : ActorMethod<[string, string, string, string], bigint>,
  'addRelease' : ActorMethod<[string, bigint, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArtist' : ActorMethod<[bigint], undefined>,
  'deleteRelease' : ActorMethod<[bigint], undefined>,
  'getArtist' : ActorMethod<[bigint], [] | [Artist]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRelease' : ActorMethod<[bigint], [] | [Release]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listArtists' : ActorMethod<[], Array<Artist>>,
  'listReleases' : ActorMethod<[], Array<Release>>,
  'listReleasesByArtist' : ActorMethod<[bigint], Array<Release>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateArtist' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateRelease' : ActorMethod<
    [bigint, string, bigint, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];