/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Artist = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'genre' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DomainActor = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Release = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'artistId' : IDL.Nat,
  'genre' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArtist' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDomainActor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRelease' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArtist' : IDL.Func([IDL.Nat], [], []),
  'deleteDomainActor' : IDL.Func([IDL.Nat], [], []),
  'deleteRelease' : IDL.Func([IDL.Nat], [], []),
  'getArtist' : IDL.Func([IDL.Nat], [IDL.Opt(Artist)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDomainActor' : IDL.Func([IDL.Nat], [IDL.Opt(DomainActor)], ['query']),
  'getRelease' : IDL.Func([IDL.Nat], [IDL.Opt(Release)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'listDomainActors' : IDL.Func([], [IDL.Vec(DomainActor)], ['query']),
  'listReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'listReleasesByArtist' : IDL.Func([IDL.Nat], [IDL.Vec(Release)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArtist' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateDomainActor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateRelease' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Artist = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'genre' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DomainActor = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Release = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'artistId' : IDL.Nat,
    'genre' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArtist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDomainActor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRelease' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArtist' : IDL.Func([IDL.Nat], [], []),
    'deleteDomainActor' : IDL.Func([IDL.Nat], [], []),
    'deleteRelease' : IDL.Func([IDL.Nat], [], []),
    'getArtist' : IDL.Func([IDL.Nat], [IDL.Opt(Artist)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDomainActor' : IDL.Func([IDL.Nat], [IDL.Opt(DomainActor)], ['query']),
    'getRelease' : IDL.Func([IDL.Nat], [IDL.Opt(Release)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'listDomainActors' : IDL.Func([], [IDL.Vec(DomainActor)], ['query']),
    'listReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'listReleasesByArtist' : IDL.Func([IDL.Nat], [IDL.Vec(Release)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArtist' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDomainActor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateRelease' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };